---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_phpmyadmin"
      tags:
        - "labocbz.install_phpmyadmin"
      vars:
        install_phpmyadmin__blowfish: "{{ inv_install_phpmyadmin__blowfish }}"
        install_phpmyadmin__install_dir: "{{ inv_install_phpmyadmin__install_dir }}"
        install_phpmyadmin__tempdir: "{{ inv_install_phpmyadmin__tempdir }}"
        install_phpmyadmin__ssl_dir: "{{ inv_install_phpmyadmin__ssl_dir }}"
        install_phpmyadmin__php_version: "{{ inv_install_phpmyadmin__php_version }}"
        install_phpmyadmin__user: "{{ inv_install_phpmyadmin__user }}"
        install_phpmyadmin__group: "{{ inv_install_phpmyadmin__group }}"
        install_phpmyadmin__dbservers: "{{ inv_install_phpmyadmin__dbservers }}"
      ansible.builtin.include_role:
        name: "labocbz.install_phpmyadmin"
